### ISSUE TITLE
ofxstatement edit-config fails when EDITOR includes binary & parameters

### ISSUE THREAD

**Issue by milankni** [kedder/ofxstatement#46]
Hi,

```
[m@tu ~]$ echo $EDITOR
/usr/bin/nano -w
[m@tu ~]$ ofxstatement edit-config
INFO: Running editor: /usr/bin/nano -w /home/m/.local/share/ofxstatement/config.ini
Traceback (most recent call last):
  File "/usr/bin/ofxstatement", line 9, in <module>
    load_entry_point('ofxstatement==0.5.0', 'console_scripts', 'ofxstatement')()
  File "/usr/lib/python3.5/site-packages/ofxstatement/tool.py", line 145, in run
    return args.func(args)
  File "/usr/lib/python3.5/site-packages/ofxstatement/tool.py", line 87, in edit_config
    subprocess.call([editor, configfname])
  File "/usr/lib/python3.5/subprocess.py", line 560, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.5/subprocess.py", line 950, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1544, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/nano -w'
```
Removing "-w" from EDITOR works around the problem.

**Comment by mcepl** [comment]
This is actually not a bug. Environmental variables are according to POSIX not supposed to be expanded, so it is absolutely correct that ofxstatement tries to run '/usr/bin/nano -w' (with space and dash in the name) executable and fails. If you want to have ``nowrap`` option set permanently, than I would advice to use ``~/.nanorc`` configuration files (see ``nanorc(5)`` manpage for more).

I would suggest WONTFIX here.

**Comment by milankni** [comment]
Ok. I agree. Thanks for the hint.
