### ISSUE TITLE
ofxstatement installation causes problem for pip3

### ISSUE THREAD

**Issue by SKelem** [kedder/ofxstatement#55]
After installing ofxstatement-0.6.0-py3.5, when I run any command with pip3, such as:
```
% pip3 help
Error processing line 3 of /usr/local/lib/python3.5/dist-packages/ofxstatement-0.6.0-py3.5-nspkg.pth:

  Traceback (most recent call last):
    File "/usr/lib/python3.5/site.py", line 173, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
    File "<frozen importlib._bootstrap>", line 574, in module_from_spec
  AttributeError: 'NoneType' object has no attribute 'loader'

Remainder of file ignored
Traceback (most recent call last):
  File "/usr/bin/pip3", line 9, in <module>
    from pip import main
  File "/usr/local/lib/python3.5/dist-packages/pip/__init__.py", line 26, in <module>
    from pip.utils import get_installed_distributions, get_prog
  File "/usr/local/lib/python3.5/dist-packages/pip/utils/__init__.py", line 27, in <module>
    from pip._vendor import pkg_resources
  File "/usr/local/lib/python3.5/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 3018, in <module>
    @_call_aside
  File "/usr/local/lib/python3.5/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 3004, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 3046, in _initialize_master_working_set
    dist.activate(replace=False)
  File "/usr/local/lib/python3.5/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 2578, in activate
    declare_namespace(pkg)
  File "/usr/local/lib/python3.5/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 2152, in declare_namespace
    _handle_ns(packageName, path_item)
  File "/usr/local/lib/python3.5/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 2092, in _handle_ns
    _rebuild_mod_path(path, packageName, module)
  File "/usr/local/lib/python3.5/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 2121, in _rebuild_mod_path
    orig_path.sort(key=position_in_sys_path)
AttributeError: '_NamespacePath' object has no attribute 'sort'`
```

If I delete /usr/local/lib/python3.5/dist-packages/ofxstatement*, then "pip3 help" works properly.

**Comment by kedder** [comment]
I can't reproduce this on my machine, so I need a bit more info:

Can you show how the contents of `/usr/local/lib/python3.5/dist-packages/ofxstatement-0.6.0-py3.5-nspkg.pth`? What version of `pip3` do you have (`pip3 --version`)?

**Comment by themalkolm** [comment]
Ye, just hit it as well.

Seems like something changed between 3.4.6 and 3.5.3 in python world.

```
$ cat Dockerfile
FROM python:3.5.3-alpine

ENV VERSION 0.6.0

RUN pip3 install ofxstatement==${VERSION}

ENTRYPOINT ["/usr/local/bin/ofxstatement"]
$ docker build -t local/ofxstatement .
...
$ docker run --rm -it local/ofxstatement
Error processing line 3 of /usr/local/lib/python3.5/site-packages/ofxstatement-0.6.0-py3.5-nspkg.pth:

  Traceback (most recent call last):
    File "/usr/local/lib/python3.5/site.py", line 167, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
    File "<frozen importlib._bootstrap>", line 574, in module_from_spec
  AttributeError: 'NoneType' object has no attribute 'loader'

Remainder of file ignored
usage: ofxstatement [-h] [--version] [-d]
                    {convert,list-plugins,edit-config} ...
```

```
$ cat Dockerfile                        
FROM python:3.4.6-alpine

ENV VERSION 0.6.0

RUN pip3 install ofxstatement==${VERSION}

ENTRYPOINT ["/usr/local/bin/ofxstatement"]
$ docker build -t local/ofxstatement .
...
$ docker run --rm -it local/ofxstatement
usage: ofxstatement [-h] [--version] [-d]
                    {convert,list-plugins,edit-config} ...
```

**Comment by themalkolm** [comment]
So.. you have this error only when no ofxstatement plugins are installed. Installing one makes this error disappear.

```
$ cat Dockerfile                                             
FROM python:3.5.3-alpine

ENV VERSION 0.6.0

RUN pip3 install ofxstatement==${VERSION}
RUN pip3 install ofxstatement-lithuanian

ENTRYPOINT ["/usr/local/bin/ofxstatement"]
$ docker build -t local/ofxstatement .
...
$ docker run --rm -it local/ofxstatement
usage: ofxstatement [-h] [--version] [-d]
                    {convert,list-plugins,edit-config} ...
```

**Comment by kedder** [comment]
@themalkolm, thank you. I was able to repro and it is starting to make sense.

That `ofxstatement-0.6.0-py3.5-nspkg.pth` is referencing `'ofxstatement.plugins'` via `importlib.machinery.PathFinder.find_spec('ofxstatement.plugins' ...`. And that thing is apparently missing unless you install any plugin.

**Comment by kedder** [comment]
ofxstatement-0.6.1 was released with the fix for this problem.

**Comment by themalkolm** [comment]
👍
