### ISSUE TITLE
AttributeError: module 'ofxstatement.plugins.alfabank' has no attribute 'AlfabankPlugin'

### ISSUE THREAD

**Issue by cedricbousmanne** [kedder/ofxstatement#82]
I just installed ofxstatement to play around with, but i'm stuck with this error while running ``ofxstatement list-plugins``

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2324, in resolve
    return functools.reduce(getattr, self.attrs, module)
AttributeError: module 'ofxstatement.plugins.alfabank' has no attribute 'AlfabankPlugin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/ofxstatement", line 11, in <module>
    load_entry_point('ofxstatement==0.6.1', 'console_scripts', 'ofxstatement')()
  File "/usr/lib/python3/dist-packages/ofxstatement/tool.py", line 150, in run
    return args.func(args)
  File "/usr/lib/python3/dist-packages/ofxstatement/tool.py", line 68, in list_plugins
    available_plugins = plugin.list_plugins()
  File "/usr/lib/python3/dist-packages/ofxstatement/plugin.py", line 26, in list_plugins
    return sorted((ep.name, ep.load()) for ep in plugin_eps)
  File "/usr/lib/python3/dist-packages/ofxstatement/plugin.py", line 26, in <genexpr>
    return sorted((ep.name, ep.load()) for ep in plugin_eps)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2316, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2326, in resolve
    raise ImportError(str(exc))
ImportError: module 'ofxstatement.plugins.alfabank' has no attribute 'AlfabankPlugin'
```

```
$ python --version
Python 2.7.14
```

Please let me know if you need additional information

**Comment by kedder** [comment]
Hi, ofxstatement doesn't support an older python 2.7. Try running it under python 3.
